import Head from "next/head";
import Header from "../components/Header";
import Showcase from "../components/ShowcaseAnime";
import AnimeCarousel from "../components/AnimeCarousel";
import { useState, useEffect } from "react";

function Animepage() {

  const [topAnime, setTopAnime] = useState([]);
  const [seasonalAnime, setSeasonalAnime] = useState([]);
  const [priorSeasonalAnime, setPriorSeasonalAnime] = useState([]);
  const [search,setSearch]=useState('Naruto')

  

  async function fetchAnimeData() {
    const top = await fetch('https://api.jikan.moe/v4/top/anime');
    const outputTop = await top.json();
    const seasons=await fetch('https://api.jikan.moe/v4/seasons/now')
    const outputSeasonal=await seasons.json()
    const priorSeasonal = await fetch('https://api.jikan.moe/v4/seasons/2022/Fall')
    const outputPriorSeasonal = await priorSeasonal.json()

    setTopAnime(outputTop.data)
    setSeasonalAnime(outputSeasonal.data)
    setPriorSeasonalAnime(outputPriorSeasonal.data)
  }
  useEffect(() => {
    fetchAnimeData()
  }, [])
  const animeDisplay=seasonalAnime.concat(priorSeasonalAnime);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Showcase animeData={animeDisplay} />
      <AnimeCarousel topAnime={topAnime} seasonalAnime={seasonalAnime}/>
    </div>
  );
}

export default Animepage
