import Head from "next/head";
import Header from "../components/Header";
import { useState, useEffect } from "react";
import HomeDisplay from "../components/HomeDisplay";
import Link from "next/link";

export default function Home() {
  const [animeList, setAnimeList] = useState([]);
  const [mangaList, setMangaList] = useState([]);
  const [search, setSearch] = useState("");

  const getSearchResult = async (query: string) => {
    const searchResultAnime = await fetch(
      `https://api.jikan.moe/v4/anime?q=${query}`
    ).then((res1) => res1.json());
    const searchResultManga = await fetch(
      `https://api.jikan.moe/v4/manga?q=${query}`
    ).then((res2) => res2.json());

    setAnimeList(searchResultAnime.data);
    setMangaList(searchResultManga.data);
  };

  const HandleSearch = (e: any) => {
    e.preventDefault();
    getSearchResult(search);
  };

  useEffect;
  return (
    <div className="">
      <Head>
        <title>Anitard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Otonari.png" />
      </Head>
      <Header />
      <main className="pb-24">
        <div className="pt-24 pl-[66vh] md:pt-24 md:pl-[20vh]">
          <div className="transition-1000">
            <Link href="/">
              <h1 className="pl-28 text-8xl font-medium font-manrope text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-pink-300 md:pl-2 hover:white">
                ANITARD
              </h1>
            </Link>
          </div>
          <div></div>
          <div className="flex items-center">
            <form className="pb-10" onSubmit={HandleSearch}>
              <input
                type="text"
                placeholder="🔍 Search here..."
                className="flex transition-200 pl-4 bg-white text-black text-justify font-semibold items-center absolute rounded-3xl h-14 w-[92vh] hover:bg-gray-200"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                required
              />
            </form>
            <div className="pt-36 pl-32">
              One place to find your favourite manga and anime!
            </div>
          </div>
        </div>
        <div className="flex justify-center gap-14 pl-10 pt-16">
          <img
            src="show4.png"
            alt="guts"
            className="h-48 w-48 rounded-full transition:1000 hover:opacity-95 md:invisible"
          />
          <img
            src="show1.png"
            alt="otonari"
            className="h-48 w-48 rounded-full transition:1000 hover:opacity-95"
          />
          <img
            src="show2.png"
            alt="mylifeamovie"
            className="h-48 w-48 rounded-full transition:1000 hover:opacity-95"
          />
          <img
            src="show3.png"
            alt="animelogo"
            className="h-48 w-48 rounded-full transition:1000 hover:opacity-95 "
          />
          <img
            src="show5.png"
            alt="Bam"
            className="h-48 w-48 rounded-full transition:1000 hover:opacity-75 md:invisible"
          />
        </div>
        <div>
          <HomeDisplay
            HandleSearch={HandleSearch}
            search={search}
            setSearch={setSearch}
            animeList={animeList}
            mangaList={mangaList}
          />
        </div>
      </main>
    </div>
  );
}
