import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import Showcase from "../components/Showcase";
import Card from "../components/Card";
import { useState, useEffect } from "react";
import { Animetype, Welcome } from "../types";
import { Anime, Character, Manga } from "@shineiichijo/marika"; 
const animeClient = new Anime();
const charaClient = new Character();
const mangaClient = new Manga();


export default function Home() {

  const [topAnime, setTopAnime] = useState([]);
  const [genreAnime, setGenreAnime] = useState([]);
  const [search,setSearch]=useState('Naruto')

  

  async function fetchAnimeData() {
    const top = await fetch('https://api.jikan.moe/v4/top/anime');
    const outputTop = await top.json();
    const seasons=await fetch('https://api.jikan.moe/v4/seasons/now')
    const outputGenre=await seasons.json()
    setTopAnime(outputTop.data)
    setGenreAnime(outputGenre.data)
  }
  console.log(topAnime)
  useEffect(() => {
    fetchAnimeData()
  }, [])

  return (
    <div className="overflow-y">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Showcase animeData={topAnime} />
      <Card topAnime={topAnime} 
            genreAnime={genreAnime}/>
    </div>
  );
}
