import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import ShowcaseManga from "../components/ShowcaseManga";
import AnimeCarousel from "../components/AnimeCarousel";
import { useState, useEffect } from "react";
import { Animetype, Welcome } from "../types";
import { Anime, Character, Manga } from "@shineiichijo/marika"; 
import MangaCarousel from "../components/MangaCarousel";
const animeClient = new Anime();
const charaClient = new Character();
const mangaClient = new Manga();


function Mangapage() {

  const [topManga, setTopManga] = useState([]);
  const [manwha, setManwha] = useState([]);
  const [search,setSearch]=useState('Naruto')

  

  async function fetchAnimeData() {
    const topManga = await fetch('https://api.jikan.moe/v4/top/manga');
    const outputTopManga = await topManga.json();
    const random=await fetch('https://api.jikan.moe/v4/top/manga?type=manhwa')
    const outputManwha=await random.json()
    setTopManga(outputTopManga.data)
    setManwha(outputManwha.data)
  }

  useEffect(() => {
    fetchAnimeData()
  }, [])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ShowcaseManga topManga={topManga} />
      <MangaCarousel topManga={topManga}
                     manwha={manwha}
      />
    </div>
  );
}

export default Mangapage
